#!/usr/bin/env bash
app_full="Dotfiles Manager"

majour="0"
minor="0"
fix="0"
branch="alpha"

__version(){
  v_number="${majour}.${minor}.${fix} (${branch})"
  echo "${app_full} v${v_number}"
}

__use(){
  :
}


_update(){
  :
}

_bash_module(){
  :
}

_edit_module(){
  :
}

__debug(){
  :
}

_main(){
  MODE=()

  #echo "option addded: $#"
  #echo "option view: $@"
  #echo "Optind: $-"

  for opt in $@
  do
    case $opt in
      --test) echo "test mode";shift;;
      --release) echo "release mode";shift;;
      -h|--help)
        __use;
        exit 0;;
      -V|--version)
          __version;
          exit 0;;
      -v|--verbose)
        VERVOSE_MODE="true";
        shift;;
      --debug)
          DEBUG_MODE=true;
          __debug "Debug mode is enable";
          shift;;
#      -*|--*)
#        echo "Ignore Option $opt";
#        shift;;
      *)
        if [[ -n "$opt" ]] && [[ ! "$opt" =~ ^-+ ]];then
          MODE+=("$opt");shift
        fi;;
    esac
  done
  echo "get main command: $MODE"
  echo "Opt: $opt"
}

_main $@
